spring:
  application:
    name: sender

  config:
    import: file:.env[.properties]

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: sender
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.use.type.headers: false
        spring.json.value.default.type: dev.cake.sender.messaging.event.EmailVerificationRequestedEvent
        spring.json.trusted.packages: dev.cake.sender.messaging.event

mail:
  host: in-v3.mailjet.com
  port: 587
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  from: ${MAIL_FROM}
  smtp-auth-enabled: true
  tls-enabled: true

#mail:
#  host: smtp.gmail.com
#  port: 587
#  username: ${MAIL_USERNAME}
#  password: ${MAIL_PASSWORD}
#  from: ${MAIL_FROM}
#  smtp-auth-enabled: true
#  tls-enabled: true

app:
  kafka:
    topics:
      email-verification-requested:
        name: auth.email-verification-requested
        replicas: 1

server:
  port: 8081
